# Generated by Django 3.1.3 on 2020-11-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='topper1',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topper2',
            new_name='topping2',
        ),
    ]
